#!/usr/bin/env bash

###################################################################
# About :
#
# axiom-fleet lets you spin up fleets of axiom instances in one or multiple regions.
# You can specify the name of a fleet (fleet prefix) or have axiom choose for you.
#
# Examples:
#
# axiom-fleet # Spin up three instances, let axiom decide on the fleet prefix"
# axiom-fleet javis -i 10 # Spin up 10 instances with a fleet prefix of javis, this will create 10 instances named javis01 to javis10."
# axiom-fleet jerry -i 25 --regions dal13,lon06,fra05,tok05,syd05 # Spin up 25 instances using round robbin region distribution"

###########################################################################################################
# Header
#
AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
source "$AXIOM_PATH/interact/includes/system-notification.sh"

provider="$(jq -r ".provider" "$AXIOM_PATH"/axiom.json)"
if [ -f "$AXIOM_PATH/providers/$provider-functions.sh" ]; then
    source "$AXIOM_PATH/providers/$provider-functions.sh"
fi

###########################################################################################################
# Help Menu
#
function usage() {
    echo -e "${BWhite}Usage:${Color_Off} axiom-fleet [OPTIONS] [<fleet prefix>]"
    echo
    echo -e "${BWhite}Description:${Color_Off}"
    echo -e "  Spin up fleets of Axiom instances across one or more regions."
    echo -e "  Specify a custom fleet prefix, or let Axiom generate one randomly."
    echo
    echo -e "${BWhite}Options:${Color_Off}"
    echo -e "  <fleet prefix>           Optional name for fleet prefix (e.g. ctbb, jerry)"
    echo -e "  -i, --instances <int>    Number of instances to create (required)"
    echo -e "  -r, --regions <list>     Comma-separated list of regions (optional)"
    echo -e "  --image <name>           Specify image to use (default from axiom.json)"
    echo -e "  --debug                  Enable debug mode (very verbose)"
    echo -e "  --help                   Show this help menu"
    echo
    echo -e "${BWhite}Examples:${Color_Off}"
    echo -e "  ${BGreen}axiom-fleet ctbb${Color_Off}                                  # Spin up 3 instances: ctbb01, ctbb02, ctbb03"
    echo -e "  ${BGreen}axiom-fleet -i 10${Color_Off}                                 # Spin up 10 instances with random prefix"
    echo -e "  ${BGreen}axiom-fleet jerry -i 25 --regions dal13,lon06,fra05${Color_Off} # Create 25 'jerry' instances using region round-robin"
    echo
}


if [[ "$provider" == "bitlaunch" ]]; then
    pass=()
    i=0
    args=""
    amount=""
    for arg in "$@"
    do
        i=$((i+1))
        if [[  ! " ${pass[@]} " =~ " ${i} " ]]; then
            set=false
            if [[ "$arg" == "-i" ]] || [[ "$arg" == "--instances" ]]; then
                n=$((i+1))
                amount=$(echo ${!n})
                set=true
                pass+=($i)
                pass+=($n)
            fi
            if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]] ; then
                usage
                exit
            fi
            if  [[ "$set" != "true" ]]; then
                space=" "
                if [[ $arg =~ $space ]]; then
                  args="$args \"$arg\""
                else
                  args="$args $arg"
                fi
            fi
        fi
    done
    gen_name=$(echo "$args" | xargs)

    if [ -z "$amount" ]; then
        echo "Error: -i, --instances <count> is a required argument."
        exit 1
    fi

    if [[ ! "$amount" =~ ^[0-9]+$ ]]; then
        echo "Error: instance count must be a number."
        exit 1
    fi

    if [ "$amount" -gt 5 ]; then
        echo "Warning: Bitlaunch provider supports a maximum of 5 instances. Setting instance count to 5."
        amount=5
    fi

    if [ -z "$gen_name" ]; then
        gen_name="${names[$RANDOM % ${#names[@]} ]}"
    fi

    echo "Initializing fleet '$gen_name' with $amount instance(s) on Bitlaunch..."
    echo -e "${BWhite}INITIALIZING IN 5 SECONDS, CTRL+C to quit... ${Color_Off}"
    sleep 5

    TOKEN=$(jq -r '.token' "$AXIOM_PATH/accounts/bitlaunch.json")
    if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
        echo "Error: Bitlaunch token not found in $AXIOM_PATH/accounts/bitlaunch.json"
        echo "Please run 'axiom-account-setup' to configure your Bitlaunch account."
        exit 1
    fi

    REGION=$(jq -r '.region' "$AXIOM_PATH/axiom.json")
    IMAGE=$(jq -r '.default_image' "$AXIOM_PATH/axiom.json")
    SIZE=$(jq -r '.default_size' "$AXIOM_PATH/axiom.json")
    SSHKEY_ID=$(jq -r '.sshkey_id' "$AXIOM_PATH/axiom.json")
    if [ -z "$SSHKEY_ID" ] || [ "$SSHKEY_ID" == "null" ]; then
        echo "Error: sshkey_id not found in axiom.json."
        echo "Please run 'axiom-build' to sync your SSH key with Bitlaunch."
        exit 1
    fi

    instance_ids=()
    total=$(blcli server list --token "$TOKEN" | jq -r --arg name "$gen_name" '.[] | select(.name | startswith($name)) | .name' | sed -n 's/.*[^0-9]\([0-9]*\)$/\1/p' | sort -nr | head -n1)
    total="${total#0}"
    start=$((total + 1))
    end=$((total + amount))

    for i in $(seq $start $end); do
        num=$(printf "%02d" $i)
        instance_name="${gen_name}${num}"
        echo "Creating instance: $instance_name"

        create_output=$(blcli server create --host bitlaunch --name "$instance_name" --region "$REGION" --image "$IMAGE" --size "$SIZE" --sshkey "$SSHKEY_ID" --token "$TOKEN")

        if [[ "$create_output" == "Error"* ]]; then
            echo "Error creating instance $instance_name: $create_output"
            echo "Aborting fleet creation."
            exit 1
        fi

        instance_id=$(echo "$create_output" | jq -r '.id')
        if [ -z "$instance_id" ] || [ "$instance_id" == "null" ]; then
            echo "Failed to get instance ID for $instance_name from output: $create_output"
            exit 1
        fi
        instance_ids+=("$instance_id")
        echo "Instance $instance_name created with ID: $instance_id"
        sleep 1
    done

    echo "All create requests sent. Waiting for instances to become available... (this may take up to 2 minutes)"
    sleep 120

    instance_ips=()
    all_ips_found=false
    echo "Polling for instance IPs..."
    for _ in $(seq 1 30); do
        list_output=$(blcli server list --token "$TOKEN")
        if [[ "$list_output" == "Error"* ]]; then
            echo "Error listing servers: $list_output"
            echo "Will retry in 10 seconds..."
            sleep 10
            continue
        fi

        temp_ips=()
        all_ok=true
        for id in "${instance_ids[@]}"; do
            server_json=$(echo "$list_output" | jq -r --arg id "$id" '.[] | select(.id == $id)')
            if [ -z "$server_json" ]; then
                all_ok=false
                break
            fi
            ip=$(echo "$server_json" | jq -r '.ipv4')
            status=$(echo "$server_json" | jq -r '.status')
            if [ -z "$ip" ] || [ "$ip" == "" ] || [ "$status" != "ok" ]; then
                all_ok=false
                break
            fi
            temp_ips+=("$ip")
        done

        if [ "$all_ok" = true ] && [ "${#temp_ips[@]}" -eq "$amount" ]; then
            instance_ips=("${temp_ips[@]}")
            all_ips_found=true
            break
        fi
        found_count=${#temp_ips[@]}
        echo -ne ">> Found IPs for $found_count/$amount instances. Waiting 10 seconds...\033[0K\r"
        sleep 10
    done
    echo ""

    if [ "$all_ips_found" = false ]; then
        echo "Error: Could not retrieve IPs for all instances after waiting."
        echo "You may need to destroy them manually: axiom-rm $gen_name* -f"
        exit 1
    fi

    echo "All instance IPs acquired."

    inventory_file="$AXIOM_PATH/images/deploy/inventory.ini"
    playbook_file="$AXIOM_PATH/images/deploy/deploy-ax.yml"
    
    if [ ! -f "$playbook_file" ]; then
        echo "Error: Ansible playbook not found at $playbook_file"
        exit 1
    fi

    echo "[cloud_vps]" > "$inventory_file"
    for ip in "${instance_ips[@]}"; do
        echo "$ip ansible_user=root" >> "$inventory_file"
    done

    echo "Generated Ansible inventory file:"
    cat "$inventory_file"

    echo "Running Ansible playbook to provision instances..."
    
    ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i "$inventory_file" "$playbook_file"

    if [ $? -eq 0 ]; then
        echo -e "${BGreen}Fleet '$gen_name' provisioned successfully!${Color_Off}"
        "$AXIOM_PATH"/interact/axiom-select "$gen_name*"
        echo -e "${BGreen}To delete your fleet, just run '${BGreen}axiom-rm \"$gen_name*\" -f${BGreen}'${Color_Off}"
    else
        echo "Error during Ansible provisioning."
        echo "You may need to destroy the instances manually: axiom-rm $gen_name* -f"
        exit 1
    fi

    exit 0
fi


BASEOS="$(uname)"
case $BASEOS in
'Darwin')
    PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
    ;;
*) ;;
esac

###########################################################################################################
# Declare defaut variables
#
spend=false
hours=false
amount=false
prompt=false
region=false
image=false
cycle_regions=false
region_array=()
gen_name=""
provider="$(jq -r ".provider" "$AXIOM_PATH"/axiom.json)"
image="$(jq -r '.imageid' "$AXIOM_PATH"/axiom.json)"
if [[ "$provider" == "bitlaunch" && ( "$image" == "null" || -z "$image") ]]; then
    image=$(jq -r '.default_image' "$AXIOM_PATH"/axiom.json)
fi
region="$(jq -r '.region' "$AXIOM_PATH"/axiom.json)"
sshkey="$(jq -r '.sshkey' "$AXIOM_PATH"/axiom.json)"
image_id=""
instances=false
time=320
init_timeout=4
init_sleep=4
manual_image_id=false

###########################################################################################################
# DO Region Transfer
# Transfer image to region if requested in that region yet does not exist. DO only
#
region_transfer(){
if [[ "$provider" == "do" ]]; then
 avail_image_id_regions=$(doctl compute image get "$image_id" -o json| jq -r '.[] | .regions[]')
 requested_image_id_regions="$regionargs"
 if [[ "$avail_image_id_regions" != *"$requested_image_id_regions"* ]]; then
  echo -e "${Color_Off}]"
  echo -e "${BYellow}instance ${BGreen}"$name"${BYellow} requested image in region ${BRed}$regionargs${BYellow}, however image ${BRed}$image${BYellow} only exists in ${BRed}$(echo $avail_image_id_regions | tr '\n' ',')"
  echo -e "${BYellow}axiom will attempt to transfer image to new region, this can take a few minutes please be patient...${Color_Off}"
  doctl compute image-action transfer $image_id --region $regionargs --wait
   if [ $? -eq 0 ]; then
    echo -e "\033[32mimage transfer succeeded\033[0m"
    echo -e "${BWhite}waiting 90 seconds before continuing...${Color_Off}"
    sleep 90
   else
    echo -e "${BRed}image transfer failed... you might need to pick a different region. '${BWhite}axiom-region ls${BRed}' to list regions. '${BWhite}axiom-images ls${BRed}' to list images${Color_Off}"
   fi
 echo -n -e "${BWhite}Instances: ${Color_Off}[ ${BGreen}"
 fi
echo -n -e ${BGreen}
fi
}

###########################################################################################################
# Parse command line arguments
#
if [ $# -eq 0 ]; then
    usage
    exit 0
fi
i=0
for arg in "$@"
do
    if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]] ; then
	usage
	exit
    fi
    i=$((i+1))
    if [[  ! " ${pass[@]} " =~ " ${i} " ]]; then
        set=false
        if [[ "$arg" == "--debug" ]]; then
            set -xv
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "-i" ]] || [[ "$arg" == "--instances" ]]; then
            n=$((i+1))
            instances=true
            amount=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if [[ "$arg" == "--regions" ]] || [[ "$arg" == "-r" ]]; then
            n=$((i+1))
            cycle_regions=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if [[ "$arg" == "--image" ]] ; then
            n=$((i+1))
            image=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
	fi
        if [[ "$arg" == "--image-id" ]]; then
            n=$((i+1))
            manual_image_id=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if  [[ "$set" != "true" ]]; then
            space=" "
            if [[ $arg =~ $space ]]; then
              args="$args \"$arg\""
            else
              args="$args $arg"
            fi
        fi
    fi
done

###########################################################################################################
# If -i /--instances isnt used, default to three instances
#
if [[ "$amount" == "false" ]]; then
 amount=3
fi

###########################################################################################################
# Generate name
#
if [ -z ${args+x} ]; then 
 gen_name="${names[$RANDOM % ${#names[@]} ]}"
else
 gen_name=$(echo "$args" | tr -d ' ')
fi

###########################################################################################################
# Change init_sleep as needed
#
if [[ "$provider" == "linode" ]]; then
 init_sleep=6
fi

###########################################################################################################
# Get image_id from $image ( default is from axiom.json ) or from user supplied manual image id param
#
if [ "$manual_image_id" != "false" ]
then
    image_id="$manual_image_id"
else
    image_id="$(get_image_id "$image")"
    if [ -z "$image_id" ]; then
        echo -e "${BRed}ERROR: imageid ${Color_Off}[ ${BBlue}$image ${Color_Off}]${BRed} not found in ${Color_Off}[ ${BBlue}~/.axiom/axiom.json ${Color_Off}]${BRed}. you may need to run ${Color_Off}[ ${BBlue}axiom-build --setup ${Color_Off}]${BRed} to build a new image."
        echo -e "${BRed}if you've already built an image, list all images with ${Color_Off}[ ${BBlue}axiom-images ls ${Color_Off}]${BRed} and select it with ${Color_Off}[ ${BBlue}axiom-images select axiom-\$provisioner-\$timestamp ${Color_Off}]"
        echo -e "${BRed}exiting...${Color_Off}"
        exit 1
    fi
fi

###########################################################################################################
# Check if ssh key is specified in axiom.json
#
if [ "$sshkey" == "" ] || [ "$sshkey" == "null" ]; then
echo -e  "${BYellow}WARNING: sshkey not found in ${Color_Off}[ ${BBlue}~/.axiom/axiom.json ${Color_Off}]${BYellow}. adding ${Color_Off}[ ${BBlue}axiom_rsa ${Color_Off}] ${BYellow}key as a backup."
account_path=$(ls -la "$AXIOM_PATH"/axiom.json | rev | cut -d " " -f 1 | rev)
sshkey=axiom_rsa
 if [ -f ~/.ssh/axiom_rsa ] ; then
  jq '.sshkey="'axiom_rsa'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"

 else
  ssh-keygen -b 2048 -t rsa -f ~/.ssh/axiom_rsa -q -N ""
  jq '.sshkey="'axiom_rsa'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"  >> /dev/null 2>&1
 fi
fi


###########################################################################################################
# Initialize fleet
#
if [[ "$cycle_regions" == "false" ]]; then

# Chance to cancel initialization of fleet
#
echo -e "${BWhite}Initializing new fleet '${BGreen}$gen_name${BWhite}' with '${BGreen}$amount${BWhite}' instances using image '${BGreen}$image${BWhite}' in region '${BGreen}$region${BWhite}'${Color_Off}...${Color_Off}"
echo -e "${BWhite}INITIALIZING IN 5 SECONDS, CTRL+C to quit... ${Color_Off}"
sleep 5

total=$(query_instances "$gen_name*" | tr " " "\n" | sed -n 's/.*[^0-9]\([0-9]*\)$/\1/p' | sort -nr | head -n1)
total="${total#0}"
start="${start#0}"
start=$((total))
amount=$(($amount+$start))
start=$((start+1))
total_spend_per_instance_rounded="0"
slug=$(cat "$AXIOM_PATH"/axiom.json | jq -r .default_size)  >/dev/null 2>&1

echo -n -e "${BWhite}Instances: ${Color_Off}[ ${BGreen}"
o=0
for i in $(seq -f "%02g" $start $amount)
do
 time=$((time+3))
 name="$gen_name$i"
 echo -n -e "${BGreen}$name ${Color_Off}"
 args=""
"$AXIOM_PATH"/interact/axiom-init "$name" --quiet --size "$slug" --image-id "$image_id" --no-select --region  "$region" &
sleep $init_sleep
o=$((o+1))
done
echo -n -e "${Color_Off} ]\n"

while [[ $time -gt 0 ]]; do
    echo -ne ">> T-Minus $time to fleet $gen_name initialization...\033[0K\r"
    sleep 1
    : $((time--))
done
fi

###########################################################################################################
# Round Robin distribution logic here ( i.e. regions_to_cycle)
#
if [[ "$cycle_regions" != "false" ]]; then

###########################################################################################################
# Chance to cancel initialization of fleet
#
echo -e "${BWhite}Initializing new fleet '${BGreen}$gen_name${BWhite}' with '${BGreen}$amount${BWhite}' instances using image '${BGreen}$image${Color_Off}'...${Color_Off}"
echo -e "${BWhite}Cycling through following regions:${BGreen}$cycle_regions${BWhite}...${Color_Off}"
echo -e "${BWhite}INITIALIZING IN 5 SECONDS, CTRL+C to quit... ${Color_Off}"
sleep 5
total=$(query_instances "$gen_name*" | tr " " "\n" | sed -n 's/.*[^0-9]\([0-9]*\)$/\1/p' | sort -nr | head -n1)
total="${total#0}"
start="${start#0}"
start=$((total))
amount=$(($amount+$start))
start=$((start+1))
total_spend_per_instance_rounded="0"
slug=$(cat "$AXIOM_PATH"/axiom.json | jq -r .default_size)  >/dev/null 2>&1

IFS=',' read -r -a region_array <<< "$cycle_regions"

# Basically repeat items, if the fleet is 20 hosts and they only supply 3 regions, loop over them until it reaches 20
total_regions=$(echo "${region_array[@]}" |  tr ' ' '\n' | wc -l | awk '{ print $1 }')
regions_to_cycle=()
 k=0
 while [[ "$(echo ${regions_to_cycle[@]} | tr ' ' '\n' | wc -l | awk '{ print $1}')" -lt "$amount" ]]
 do
  regions_to_cycle+=("${region_array[k]}")
  if [[ "$k" -lt "$total_regions" ]]; then
   k=$((k+1))
  else
   k=0
  fi
done

# Remove null element from array and reindex
#
for i in "${!regions_to_cycle[@]}"; do
  [ -n "${regions_to_cycle[$i]}" ] || unset "regions_to_cycle[$i]" && regions_to_cycle=( "${regions_to_cycle[@]}" )
done

echo -n -e "${BWhite}Instances: ${Color_Off}[ ${BGreen}"
o=0
for i in $(seq -f "%02g" $start $amount)
do
time=$((time+3))
name="$gen_name$i"
echo -n -e "${BGreen}$name ${Color_Off}"
args=""
regionargs="${regions_to_cycle[o]}"

# final check to make sure region is set
#
if [ -z ${regionargs:+x} ]; then
regionargs="$(jq -r '.region' "$AXIOM_PATH"/axiom.json)"
fi

###########################################################################################################
# DO Region Transfer
# Transfer image to region if requested in that region yet does not exist. DO only
#
if [[ "$provider" == "do" ]]; then
  region_transfer
fi

# create instance
#
"$AXIOM_PATH"/interact/axiom-init "$name" --quiet --size "$slug" --image-id "$image_id" --no-select --region  "$regionargs" &
sleep $init_sleep
o=$((o+1))
done
echo -n -e "${Color_Off} ]\n"
fi

while [[ $time -gt 0 ]]; do
 echo -ne ">> T-Minus $time to fleet $gen_name initialization...\033[0K\r"
 sleep 1
 : $((time--))
done
"$AXIOM_PATH"/interact/axiom-select "$gen_name*"

echo -e "${BGreen}Fleet started succesfully!\nTo delete your fleet, just run '${BGreen}axiom-rm \"$gen_name*\" -f${BGreen}'${Color_Off}"
